name: CMake Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Target Windows environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Vulkan SDK
        run: |
          curl -LO https://sdk.lunarg.com/sdk/download/latest/windows/vulkan-sdk.exe
          ./vulkan-sdk.exe /S /D=C:\VulkanSDK

      - name: Set Vulkan SDK environment variables
        run: |
          echo "VULKAN_SDK=C:\VulkanSDK" >> $GITHUB_ENV
          echo "VK_SDK_PATH=C:\VulkanSDK" >> $GITHUB_ENV
          echo "Adding Vulkan SDK to PATH"
          echo "$env:PATH=C:\VulkanSDK\Bin;$env:PATH" >> $GITHUB_ENV

      - name: Set up CMake 3.16
        uses: jwlawson/actions-setup-cmake@v1
        with:
          version: 3.16.0

      - name: Configure CMake
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build

      - name: Run Tests
        run: ctest --test-dir build --output-on-failure