name: CMake Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Target Windows environment



    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true  # Ensure submodules are cloned
          fetch-depth: 0     # Fetch all history for submodules

      # - name: Install Vulkan SDK
      #   run: |
      #    curl -LO https://sdk.lunarg.com/sdk/download/latest/windows/vulkan-sdk.exe
      #    ./vulkan-sdk.exe /S /D=C:\VulkanSDK  # Silent install to C:\VulkanSDK
      #   shell: cmd
  
      # - name: Set Vulkan SDK environment variables
      #   run: |
      #     echo "VULKAN_SDK=C:\VulkanSDK" >> $GITHUB_ENV
      #     echo "VK_SDK_PATH=C:\VulkanSDK" >> $GITHUB_ENV
      #     echo "Adding Vulkan SDK to PATH"
      #     echo "$VULKAN_SDK\Bin" >> $GITHUB_PATH
      #   shell: cmd
  
      # - name: Verify Vulkan SDK installation
      #   run: |
      #     echo "Vulkan SDK installed at: $VULKAN_SDK"
      #     dir $VULKAN_SDK\Bin
      #   shell: cmd
      


      # - name: Set up CMake 3.16
      #   uses: jwlawson/actions-setup-cmake@v1
      
      

      # - name: Configure CMake
      #   run: cmake -S . -B build

      # - name: Build
      #   run: cmake --build build

      # - name: Run Tests
      #   run: ctest --test-dir build --output-on-failure