name: CMake Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Target Windows environment



    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true  # Ensure submodules are cloned
          fetch-depth: 0     # Fetch all history for submodules

      - name: Install Vulkan SDK
        uses: humbletim/install-vulkan-sdk@v1.1.1
        with:
          version: 1.3.250.1
          cache: false

         
      - name: Download VMA (Vulkan Memory Allocator)
        shell: bash
        run: |
            curl -L https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/archive/refs/heads/master.zip -o vma.zip
            unzip vma.zip
            cp VulkanMemoryAllocator-master/include/vk_mem_alloc.h $VULKAN_SDK/include/vma/


      - name: Set up CMake 3.16
        uses: jwlawson/actions-setup-cmake@v1
      
      

      - name: Configure CMake
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build

      - name: Run Tests
        run: ctest --test-dir build --output-on-failure